#%RAML 1.0
title: My API
mediaType: application/json
tititatatoto: Not available here (or anywhere else)
traits:
  simpleTrait: !include traits/trait.raml
types:
  IncludedType: !include types/includedType.raml
/orgs/{orgId}:
  get:
  is: [simpleTrait: {typeName: IncludedType}]
